# Generated by Django 6.0.3 on 2026-03-25 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='bank_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
    ]
